export const randomTopics = [
    "food", "objects", "planets", "artistic stuff", "nature", "wildlife", "wind", "air",
    "fantasy creatures", "celestial bodies", "emotions", "time", "weather", "space phenomena",
    "music", "colors", "fantasy worlds", "ancient civilizations", "mythical beasts",
    "magic spells", "galaxies", "constellations", "ocean depths", "volcanic eruptions",
    "enchanted forests", "secret gardens", "time travel", "dimensional rifts", "spiritual realms",
    "hidden treasures", "parallel universes", "legendary artifacts", "lost civilizations",
    "elemental forces", "cosmic energy", "astral projection", "fairy tales", "arcane knowledge",
    "unseen forces", "mystic visions", "celestial phenomena", "supernatural beings",
    "mythological realms", "alternate realities", "ancient prophecies",
    "adventure", "technology", "outer space", "magic", "history", "mystery", "creativity",
    "imagination", "innovation", "science", "invention","exploration", "discovery",
    "wisdom", "knowledge", "curiosity", "challenge", "growth", "transformation", "inspiration",
    "motivation", "ambition", "success", "failure", "overcoming obstacles", "perseverance",
    "resilience", "courage", "bravery", "heroism", "villainy", "betrayal", "loyalty",
    "friendship", "love", "romance", "heartbreak", "forgiveness", "redemption", "justice",
    "equality", "freedom", "peace", "war", "conflict", "sacrifice", "hope", "despair",
    "survival", "adaptation", "change", "progress", "tradition", "modernization", "evolution",
    "revolution", "nature","nurture", "destiny", "fate", "karma", "duality", "balance",
    "chaos", "order", "illusion", "reality", "dream", "consciousness", "existence",
    "purpose", "meaning", "legacy", "identity", "self-discovery", "transcendence",
    "enlightenment", "faith", "belief", "religion", "spirituality", "myth", "science fiction", "fantasy", "logic",
    "individuality", "community", "society", "culture",
    "technology", "humanity", "human nature", "alienation", "belonging",
    "acceptance", "diversity", "inclusivity", "empathy", "compassion", "kindness",
    "generosity", "altruism", "selfishness", "greed", "contentment",
    "happiness", "fulfillment", "suffering", "pain", "pleasure", "joy", "sadness",
    "anger", "fear", "anxiety", "depression", "mental health", "well-being",
    "healing", "therapy", "mindfulness", "meditation", "self-care", "vulnerability",
    "strength", "weakness", "growth", "comfort", "risk", "challenge",
    "opportunity", "adversity", "overcoming fear", "cowardice", "recklessness", "solitude", "family", "parenting",
    "childhood", "aging", "youth", "generation gap", "life stages", "rites of passage",
    "journey", "quest", "routine", "wanderlust", "travel", "security", "home", "roots", "heritage",
    "education", "learning", "intellect", "intuition", "conformity", "art", "literature", "poetry", "writing", 
    "storytelling", "silence", "dance", "theater", "film", "painting", "sculpture", 
    "architecture", "photography", "design", "fashion", "style", "taste", "beauty", "aesthetics", "expression", 
    "interpretation", "perception","imitation", "originality", "authenticity", "creative process", "artist's journey", 
    "artistic vision", "purpose of art", "meaning of art", "impact of art", "commerce", "entertainment", "rebellion", 
    "reflection", "communication", "social commentary", "activism", "connection",
    "transcendence", "legacy", "identity", "memory", "celebration", "documentation", "preservation", 
    "education", "challenge", "solace", "truth", "questioning", "exploration of self"]